# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro_clientes.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastroClientes(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 565)
        MainWindow.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_razao = QtWidgets.QLineEdit(self.centralwidget)
        self.line_razao.setGeometry(QtCore.QRect(80, 50, 851, 20))
        self.line_razao.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_razao.setObjectName("line_razao")
        self.line_fantasia = QtWidgets.QLineEdit(self.centralwidget)
        self.line_fantasia.setGeometry(QtCore.QRect(90, 80, 841, 20))
        self.line_fantasia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_fantasia.setObjectName("line_fantasia")
        self.line_cnpj = QtWidgets.QLineEdit(self.centralwidget)
        self.line_cnpj.setGeometry(QtCore.QRect(45, 110, 321, 20))
        self.line_cnpj.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_cnpj.setObjectName("line_cnpj")
        self.line_estadual = QtWidgets.QLineEdit(self.centralwidget)
        self.line_estadual.setGeometry(QtCore.QRect(500, 140, 431, 20))
        self.line_estadual.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_estadual.setText("")
        self.line_estadual.setObjectName("line_estadual")
        self.line_rua = QtWidgets.QLineEdit(self.centralwidget)
        self.line_rua.setGeometry(QtCore.QRect(60, 170, 521, 20))
        self.line_rua.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_rua.setObjectName("line_rua")
        self.line_municipal = QtWidgets.QLineEdit(self.centralwidget)
        self.line_municipal.setGeometry(QtCore.QRect(110, 140, 281, 20))
        self.line_municipal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_municipal.setObjectName("line_municipal")
        self.line_bairro = QtWidgets.QLineEdit(self.centralwidget)
        self.line_bairro.setGeometry(QtCore.QRect(630, 170, 301, 20))
        self.line_bairro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_bairro.setObjectName("line_bairro")
        self.line_uf = QtWidgets.QLineEdit(self.centralwidget)
        self.line_uf.setGeometry(QtCore.QRect(470, 200, 51, 20))
        self.line_uf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_uf.setObjectName("line_uf")
        self.line_cep = QtWidgets.QLineEdit(self.centralwidget)
        self.line_cep.setGeometry(QtCore.QRect(560, 200, 171, 20))
        self.line_cep.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_cep.setObjectName("line_cep")
        self.line_cidade = QtWidgets.QLineEdit(self.centralwidget)
        self.line_cidade.setGeometry(QtCore.QRect(55, 200, 381, 20))
        self.line_cidade.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_cidade.setObjectName("line_cidade")
        self.line_tel = QtWidgets.QLineEdit(self.centralwidget)
        self.line_tel.setGeometry(QtCore.QRect(65, 230, 211, 20))
        self.line_tel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_tel.setObjectName("line_tel")
        self.line_atividade = QtWidgets.QLineEdit(self.centralwidget)
        self.line_atividade.setGeometry(QtCore.QRect(480, 110, 451, 20))
        self.line_atividade.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_atividade.setObjectName("line_atividade")
        self.line_email = QtWidgets.QLineEdit(self.centralwidget)
        self.line_email.setGeometry(QtCore.QRect(320, 230, 331, 20))
        self.line_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_email.setObjectName("line_email")
        self.label_razao = QtWidgets.QLabel(self.centralwidget)
        self.label_razao.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_razao.setObjectName("label_razao")
        self.label_fantasia = QtWidgets.QLabel(self.centralwidget)
        self.label_fantasia.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_fantasia.setObjectName("label_fantasia")
        self.label_cnpj = QtWidgets.QLabel(self.centralwidget)
        self.label_cnpj.setGeometry(QtCore.QRect(10, 110, 31, 16))
        self.label_cnpj.setObjectName("label_cnpj")
        self.label_estadual = QtWidgets.QLabel(self.centralwidget)
        self.label_estadual.setGeometry(QtCore.QRect(400, 140, 91, 16))
        self.label_estadual.setObjectName("label_estadual")
        self.label_municipal = QtWidgets.QLabel(self.centralwidget)
        self.label_municipal.setGeometry(QtCore.QRect(10, 140, 91, 16))
        self.label_municipal.setObjectName("label_municipal")
        self.label_rua = QtWidgets.QLabel(self.centralwidget)
        self.label_rua.setGeometry(QtCore.QRect(10, 170, 47, 13))
        self.label_rua.setObjectName("label_rua")
        self.label_bairro = QtWidgets.QLabel(self.centralwidget)
        self.label_bairro.setGeometry(QtCore.QRect(590, 170, 31, 16))
        self.label_bairro.setObjectName("label_bairro")
        self.label_cidade = QtWidgets.QLabel(self.centralwidget)
        self.label_cidade.setGeometry(QtCore.QRect(10, 200, 41, 16))
        self.label_cidade.setObjectName("label_cidade")
        self.label_uf = QtWidgets.QLabel(self.centralwidget)
        self.label_uf.setGeometry(QtCore.QRect(440, 200, 21, 16))
        self.label_uf.setObjectName("label_uf")
        self.label_cep = QtWidgets.QLabel(self.centralwidget)
        self.label_cep.setGeometry(QtCore.QRect(530, 200, 21, 16))
        self.label_cep.setObjectName("label_cep")
        self.label_tel = QtWidgets.QLabel(self.centralwidget)
        self.label_tel.setGeometry(QtCore.QRect(10, 230, 51, 16))
        self.label_tel.setObjectName("label_tel")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(280, 230, 31, 16))
        self.label_email.setObjectName("label_email")
        self.label_ativid = QtWidgets.QLabel(self.centralwidget)
        self.label_ativid.setGeometry(QtCore.QRect(370, 110, 101, 16))
        self.label_ativid.setObjectName("label_ativid")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(350, 0, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(320, 430, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(170, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_cadastro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cadastro.setGeometry(QtCore.QRect(480, 430, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cadastro.setFont(font)
        self.btn_cadastro.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.btn_cadastro.setObjectName("btn_cadastro")
        self.label_title2 = QtWidgets.QLabel(self.centralwidget)
        self.label_title2.setGeometry(QtCore.QRect(330, 280, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title2.setFont(font)
        self.label_title2.setObjectName("label_title2")
        self.label_ntelas = QtWidgets.QLabel(self.centralwidget)
        self.label_ntelas.setGeometry(QtCore.QRect(20, 340, 151, 16))
        self.label_ntelas.setObjectName("label_ntelas")
        self.line_ntela = QtWidgets.QLineEdit(self.centralwidget)
        self.line_ntela.setGeometry(QtCore.QRect(170, 340, 81, 20))
        self.line_ntela.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_ntela.setObjectName("line_ntela")
        self.label_formpag = QtWidgets.QLabel(self.centralwidget)
        self.label_formpag.setGeometry(QtCore.QRect(260, 340, 111, 16))
        self.label_formpag.setObjectName("label_formpag")
        self.comboBox_formpag = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_formpag.setGeometry(QtCore.QRect(370, 340, 101, 22))
        self.comboBox_formpag.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_formpag.setObjectName("comboBox_formpag")
        self.comboBox_formpag.addItem("")
        self.comboBox_formpag.addItem("")
        self.comboBox_formpag.addItem("")
        self.comboBox_formpag.addItem("")
        self.comboBox_formpag.setItemText(3, "")
        self.label_planos = QtWidgets.QLabel(self.centralwidget)
        self.label_planos.setGeometry(QtCore.QRect(480, 340, 47, 16))
        self.label_planos.setObjectName("label_planos")
        self.comboBox_planos = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_planos.setGeometry(QtCore.QRect(520, 340, 101, 22))
        self.comboBox_planos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_planos.setObjectName("comboBox_planos")
        self.comboBox_planos.addItem("")
        self.comboBox_planos.addItem("")
        self.comboBox_planos.addItem("")
        self.comboBox_planos.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 936, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastro clientes"))
        self.label_razao.setText(_translate("MainWindow", "Razão social:"))
        self.label_fantasia.setText(_translate("MainWindow", "Nome Fantasia:"))
        self.label_cnpj.setText(_translate("MainWindow", "CNPJ:"))
        self.label_estadual.setText(_translate("MainWindow", "Inscrição Estadual:"))
        self.label_municipal.setText(_translate("MainWindow", "Inscrição municipal:"))
        self.label_rua.setText(_translate("MainWindow", "Rua/Av.:"))
        self.label_bairro.setText(_translate("MainWindow", "Bairro:"))
        self.label_cidade.setText(_translate("MainWindow", "Cidade:"))
        self.label_uf.setText(_translate("MainWindow", "UF:"))
        self.label_cep.setText(_translate("MainWindow", "CEP:"))
        self.label_tel.setText(_translate("MainWindow", "Telefone:"))
        self.label_email.setText(_translate("MainWindow", "E-mail:"))
        self.label_ativid.setText(_translate("MainWindow", "Atividade do negócio:"))
        self.label_title.setText(_translate("MainWindow", "Dados da pessoa juridica"))
        self.btn_cancel.setText(_translate("MainWindow", "Cancelar"))
        self.btn_cadastro.setText(_translate("MainWindow", "Cadastrar"))
        self.label_title2.setText(_translate("MainWindow", "Dados do serviço cadastrado"))
        self.label_ntelas.setText(_translate("MainWindow", "Números de telas contratadas:"))
        self.label_formpag.setText(_translate("MainWindow", "Forma de pagamento:"))
        self.comboBox_formpag.setItemText(0, _translate("MainWindow", "Boleto"))
        self.comboBox_formpag.setItemText(1, _translate("MainWindow", "Débito"))
        self.comboBox_formpag.setItemText(2, _translate("MainWindow", "Crédito a vista"))
        self.label_planos.setText(_translate("MainWindow", "Planos:"))
        self.comboBox_planos.setItemText(0, _translate("MainWindow", "Trimestral"))
        self.comboBox_planos.setItemText(1, _translate("MainWindow", "Semestral"))
        self.comboBox_planos.setItemText(2, _translate("MainWindow", "Anual"))
        self.comboBox_planos.setItemText(3, _translate("MainWindow", "Binual"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_cadastroClientes()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
