# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gerenciamento_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gerenciamentoCliente(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1396, 784)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0);;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 110, 161, 381))
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_add = QtWidgets.QPushButton(self.frame_2)
        self.btn_add.setGeometry(QtCore.QRect(10, 150, 139, 40))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add.setFont(font)
        self.btn_add.setTabletTracking(False)
        self.btn_add.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 20, 20);\n"
"}\n"
"QPushButton:pressed{\n"
"    rgb(0, 0, 255)\n"
"}\n"
"")
        self.btn_add.setAutoDefault(False)
        self.btn_add.setFlat(False)
        self.btn_add.setObjectName("btn_add")
        self.btn_delet = QtWidgets.QPushButton(self.frame_2)
        self.btn_delet.setGeometry(QtCore.QRect(10, 200, 139, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delet.setFont(font)
        self.btn_delet.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 20, 20);\n"
"}\n"
"QPushButton:pressed{\n"
"    rgb(0, 0, 255)\n"
"}\n"
"")
        self.btn_delet.setObjectName("btn_delet")
        self.btn_exit = QtWidgets.QPushButton(self.frame_2)
        self.btn_exit.setGeometry(QtCore.QRect(10, 320, 139, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(195, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(165,165,165);\n"
"}")
        self.btn_exit.setObjectName("btn_exit")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 30, 161, 91))
        self.label.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_licenca = QtWidgets.QLabel(self.frame_2)
        self.label_licenca.setGeometry(QtCore.QRect(0, 60, 81, 20))
        self.label_licenca.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.label_licenca.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_licenca.setObjectName("label_licenca")
        self.label_disponivel_2 = QtWidgets.QLabel(self.frame_2)
        self.label_disponivel_2.setGeometry(QtCore.QRect(0, 90, 101, 20))
        self.label_disponivel_2.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.label_disponivel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_disponivel_2.setObjectName("label_disponivel_2")
        self.label_disponivel = QtWidgets.QLabel(self.frame_2)
        self.label_disponivel.setGeometry(QtCore.QRect(100, 90, 41, 20))
        self.label_disponivel.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.label_disponivel.setText("")
        self.label_disponivel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disponivel.setObjectName("label_disponivel")
        self.licenca = QtWidgets.QLabel(self.frame_2)
        self.licenca.setGeometry(QtCore.QRect(30, 30, 81, 20))
        self.licenca.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.licenca.setAlignment(QtCore.Qt.AlignCenter)
        self.licenca.setObjectName("licenca")
        self.label_used = QtWidgets.QLabel(self.frame_2)
        self.label_used.setGeometry(QtCore.QRect(80, 60, 41, 20))
        self.label_used.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.label_used.setText("")
        self.label_used.setAlignment(QtCore.Qt.AlignCenter)
        self.label_used.setObjectName("label_used")
        self.label.raise_()
        self.btn_add.raise_()
        self.btn_delet.raise_()
        self.btn_exit.raise_()
        self.label_licenca.raise_()
        self.label_disponivel_2.raise_()
        self.label_disponivel.raise_()
        self.licenca.raise_()
        self.label_used.raise_()
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(180, 10, 1171, 701))
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 3302, 4514))
        self.scrollAreaWidgetContents_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.graficSemanal_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graficSemanal_2.sizePolicy().hasHeightForWidth())
        self.graficSemanal_2.setSizePolicy(sizePolicy)
        self.graficSemanal_2.setMinimumSize(QtCore.QSize(1100, 700))
        self.graficSemanal_2.setMaximumSize(QtCore.QSize(1100, 700))
        self.graficSemanal_2.setAutoFillBackground(False)
        self.graficSemanal_2.setText("")
        self.graficSemanal_2.setScaledContents(False)
        self.graficSemanal_2.setAlignment(QtCore.Qt.AlignCenter)
        self.graficSemanal_2.setObjectName("graficSemanal_2")
        self.horizontalLayout_5.addWidget(self.graficSemanal_2)
        self.graficSemanal_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graficSemanal_1.sizePolicy().hasHeightForWidth())
        self.graficSemanal_1.setSizePolicy(sizePolicy)
        self.graficSemanal_1.setMinimumSize(QtCore.QSize(1100, 700))
        self.graficSemanal_1.setMaximumSize(QtCore.QSize(1100, 700))
        self.graficSemanal_1.setAutoFillBackground(False)
        self.graficSemanal_1.setText("")
        self.graficSemanal_1.setScaledContents(False)
        self.graficSemanal_1.setAlignment(QtCore.Qt.AlignCenter)
        self.graficSemanal_1.setObjectName("graficSemanal_1")
        self.horizontalLayout_5.addWidget(self.graficSemanal_1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.grafig_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.grafig_4.setMinimumSize(QtCore.QSize(500, 500))
        self.grafig_4.setMaximumSize(QtCore.QSize(500, 500))
        self.grafig_4.setAutoFillBackground(False)
        self.grafig_4.setText("")
        self.grafig_4.setScaledContents(False)
        self.grafig_4.setAlignment(QtCore.Qt.AlignCenter)
        self.grafig_4.setObjectName("grafig_4")
        self.horizontalLayout_4.addWidget(self.grafig_4)
        self.grafig_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.grafig_5.setMinimumSize(QtCore.QSize(500, 500))
        self.grafig_5.setMaximumSize(QtCore.QSize(500, 500))
        self.grafig_5.setAutoFillBackground(False)
        self.grafig_5.setText("")
        self.grafig_5.setScaledContents(False)
        self.grafig_5.setAlignment(QtCore.Qt.AlignCenter)
        self.grafig_5.setObjectName("grafig_5")
        self.horizontalLayout_4.addWidget(self.grafig_5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graficSemanal_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.graficSemanal_4.setMinimumSize(QtCore.QSize(1100, 700))
        self.graficSemanal_4.setMaximumSize(QtCore.QSize(1100, 700))
        self.graficSemanal_4.setAutoFillBackground(False)
        self.graficSemanal_4.setText("")
        self.graficSemanal_4.setScaledContents(False)
        self.graficSemanal_4.setAlignment(QtCore.Qt.AlignCenter)
        self.graficSemanal_4.setObjectName("graficSemanal_4")
        self.horizontalLayout.addWidget(self.graficSemanal_4)
        self.graficSemanal_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graficSemanal_3.sizePolicy().hasHeightForWidth())
        self.graficSemanal_3.setSizePolicy(sizePolicy)
        self.graficSemanal_3.setMinimumSize(QtCore.QSize(1100, 700))
        self.graficSemanal_3.setMaximumSize(QtCore.QSize(1100, 700))
        self.graficSemanal_3.setAutoFillBackground(False)
        self.graficSemanal_3.setText("")
        self.graficSemanal_3.setScaledContents(False)
        self.graficSemanal_3.setAlignment(QtCore.Qt.AlignCenter)
        self.graficSemanal_3.setObjectName("graficSemanal_3")
        self.horizontalLayout.addWidget(self.graficSemanal_3)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graficSemanal_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.graficSemanal_5.setMinimumSize(QtCore.QSize(1100, 700))
        self.graficSemanal_5.setMaximumSize(QtCore.QSize(1100, 700))
        self.graficSemanal_5.setAutoFillBackground(False)
        self.graficSemanal_5.setText("")
        self.graficSemanal_5.setScaledContents(False)
        self.graficSemanal_5.setAlignment(QtCore.Qt.AlignCenter)
        self.graficSemanal_5.setObjectName("graficSemanal_5")
        self.horizontalLayout_2.addWidget(self.graficSemanal_5)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.grafig_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.grafig_1.setMinimumSize(QtCore.QSize(500, 500))
        self.grafig_1.setMaximumSize(QtCore.QSize(500, 500))
        self.grafig_1.setAutoFillBackground(False)
        self.grafig_1.setText("")
        self.grafig_1.setScaledContents(False)
        self.grafig_1.setAlignment(QtCore.Qt.AlignCenter)
        self.grafig_1.setWordWrap(False)
        self.grafig_1.setObjectName("grafig_1")
        self.horizontalLayout_3.addWidget(self.grafig_1)
        self.grafig_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.grafig_2.setMinimumSize(QtCore.QSize(500, 500))
        self.grafig_2.setMaximumSize(QtCore.QSize(500, 500))
        self.grafig_2.setAutoFillBackground(False)
        self.grafig_2.setText("")
        self.grafig_2.setScaledContents(False)
        self.grafig_2.setAlignment(QtCore.Qt.AlignCenter)
        self.grafig_2.setObjectName("grafig_2")
        self.horizontalLayout_3.addWidget(self.grafig_2)
        self.grafig_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.grafig_3.setMinimumSize(QtCore.QSize(500, 500))
        self.grafig_3.setMaximumSize(QtCore.QSize(500, 500))
        self.grafig_3.setAutoFillBackground(False)
        self.grafig_3.setText("")
        self.grafig_3.setScaledContents(False)
        self.grafig_3.setAlignment(QtCore.Qt.AlignCenter)
        self.grafig_3.setObjectName("grafig_3")
        self.horizontalLayout_3.addWidget(self.grafig_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.grafigEquipe_mes1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.grafigEquipe_mes1.setMinimumSize(QtCore.QSize(1100, 700))
        self.grafigEquipe_mes1.setMaximumSize(QtCore.QSize(1100, 700))
        self.grafigEquipe_mes1.setText("")
        self.grafigEquipe_mes1.setObjectName("grafigEquipe_mes1")
        self.horizontalLayout_6.addWidget(self.grafigEquipe_mes1)
        self.grafigEquipe_mes2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.grafigEquipe_mes2.setMinimumSize(QtCore.QSize(1100, 700))
        self.grafigEquipe_mes2.setMaximumSize(QtCore.QSize(1100, 700))
        self.grafigEquipe_mes2.setText("")
        self.grafigEquipe_mes2.setObjectName("grafigEquipe_mes2")
        self.horizontalLayout_6.addWidget(self.grafigEquipe_mes2)
        self.grafigEquipe_mes = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.grafigEquipe_mes.setMinimumSize(QtCore.QSize(1100, 700))
        self.grafigEquipe_mes.setMaximumSize(QtCore.QSize(1100, 700))
        self.grafigEquipe_mes.setText("")
        self.grafigEquipe_mes.setScaledContents(True)
        self.grafigEquipe_mes.setAlignment(QtCore.Qt.AlignCenter)
        self.grafigEquipe_mes.setObjectName("grafigEquipe_mes")
        self.horizontalLayout_6.addWidget(self.grafigEquipe_mes)
        self.gridLayout.addLayout(self.horizontalLayout_6, 7, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.grafigEquipe_mes4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.grafigEquipe_mes4.setMinimumSize(QtCore.QSize(1100, 700))
        self.grafigEquipe_mes4.setMaximumSize(QtCore.QSize(1100, 700))
        self.grafigEquipe_mes4.setText("")
        self.grafigEquipe_mes4.setObjectName("grafigEquipe_mes4")
        self.horizontalLayout_7.addWidget(self.grafigEquipe_mes4)
        self.grafigEquipe_mes3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.grafigEquipe_mes3.setMinimumSize(QtCore.QSize(1100, 700))
        self.grafigEquipe_mes3.setMaximumSize(QtCore.QSize(1100, 700))
        self.grafigEquipe_mes3.setText("")
        self.grafigEquipe_mes3.setObjectName("grafigEquipe_mes3")
        self.horizontalLayout_7.addWidget(self.grafigEquipe_mes3)
        self.gridLayout.addLayout(self.horizontalLayout_7, 8, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 161, 91))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../modulos/coderpro_login.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAdicionar = QtWidgets.QAction(MainWindow)
        self.actionAdicionar.setObjectName("actionAdicionar")
        self.actionAlterar = QtWidgets.QAction(MainWindow)
        self.actionAlterar.setObjectName("actionAlterar")
        self.actionDeletar = QtWidgets.QAction(MainWindow)
        self.actionDeletar.setObjectName("actionDeletar")
        self.actionProcurar = QtWidgets.QAction(MainWindow)
        self.actionProcurar.setObjectName("actionProcurar")
        self.actionGerar_relat_rio = QtWidgets.QAction(MainWindow)
        self.actionGerar_relat_rio.setObjectName("actionGerar_relat_rio")
        self.actionRecarregar = QtWidgets.QAction(MainWindow)
        self.actionRecarregar.setObjectName("actionRecarregar")
        self.actionIndividual = QtWidgets.QAction(MainWindow)
        self.actionIndividual.setObjectName("actionIndividual")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gerenciamento"))
        self.btn_add.setText(_translate("MainWindow", "Adicionar"))
        self.btn_delet.setText(_translate("MainWindow", "Deletar"))
        self.btn_exit.setText(_translate("MainWindow", "Sair"))
        self.label_licenca.setText(_translate("MainWindow", " Licenças em uso:"))
        self.label_disponivel_2.setText(_translate("MainWindow", " Licenças disponiveis:"))
        self.licenca.setText(_translate("MainWindow", "Licenças"))
        self.actionAdicionar.setText(_translate("MainWindow", "Adicionar"))
        self.actionAlterar.setText(_translate("MainWindow", "Alterar"))
        self.actionDeletar.setText(_translate("MainWindow", "Deletar"))
        self.actionProcurar.setText(_translate("MainWindow", "Procurar"))
        self.actionGerar_relat_rio.setText(_translate("MainWindow", "Gerar relatório"))
        self.actionRecarregar.setText(_translate("MainWindow", "Recarregar"))
        self.actionIndividual.setText(_translate("MainWindow", "Individual"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_gerenciamentoCliente()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
